const projects = [
   {
    name: 'ImSeekingGeeks - Online Dating App',
    dateStarted: '',
    dateCompeleted: ``,
    description: 'ImSeekingGeeks is an online dating platform only available in the US that lets you the meet the most amazing singles.',
    mainImage: './images/fulls/online-dating-promo-main.jpg',
    mainUrl: '',
    documentsLinks: [],
    github: 'https://github.com/dwoods447/online_dating_app',
    skillsUsed: [
      'nuxt.js',
      'node.js',
      'express.js',
      'mongodb',
    ],
    databases: [
        'mongodb'
    ],
    techIcons: [],
    imageUrls:[],
    modalLink: '#animatedModal-8',
    modalId: 'modal08',
   },
//    {
//     name: '',
//     date: '',
//     description: '',
//     mainImage: 'images/fulls/movie_guide.png',
//     mainUrl: '',
//     documentsLinks: [],
//     github: 'https://github.com/dwoods447/my_movie_guide',
//     skillsUsed: [
//       'nuxt.js',
//       'node.js',
//       'express.js',
//       'mongodb',
//     ],
//     databases: [],
//     techIcons: [],
//     imageUrls:[],
//     modalLink: '#animatedModal-7',
//     modalId: 'modal07',
//    },
   {
    name: 'Online Italian Restauraunt App',
    date: '',
    description: 'The Online Itailian Restauraunt allows customers to place an order from the website.',
    mainImage: 'images/fulls/itlalian-restauraunt.png',
    mainUrl: '',
    documentsLinks: [],
    github: 'https://github.com/dwoods447/online_restauraunt',
    skillsUsed: [
        'vue.js',
        'node.js',
        'postgres',
        'express.js',
        'vuex',
        'boostrapvue',
        'axios',
        'vue-router',
        'moment.js',
        'smartystreets API',
        'sequelize ORM'
    ],
    databases: [
        'postgres'
    ],
    techIcons: [],
    imageUrls:[],
    modalLink: '#animatedModal-6',
    modalId: 'modal06',
   },
   {
    name: 'Apex Legends Stat Tracker',
    date: '',
    description: 'The Apex Legends Stat Tracker is a simple Full Stack Application that utilizes the Tracker Network API to track player stats',
    mainImage: 'images/fulls/apex-legends-tracker.png',
    mainUrl: '',
    documentsLinks: [],
    github: 'https://github.com/dwoods447/apex-legends-stat-tracker',
    skillsUsed: [
        'vue.js',
        'node.js',
        'express.js',
        'vuetify',
        'vee-validate',
        'vue-router',
        'axios'
    ],
    databases: [],
    techIcons: [],
    imageUrls:[],
    modalLink: '',
    modalId: '',
   },
   {
    name: 'Online Book Store App',
    date: '',
    description: 'Web application where users are able to purchase books.',
    mainImage: 'images/fulls/online-bookstore.jpg',
    mainUrl: '',
    documentsLinks: [],
    github: 'https://github.com/dwoods447/online-store',
    skillsUsed: [
        'vue.js',
        'node.js',
        'express.js',
        'vuetify',
        'vee-validate',
        'vue-router',
        'axios'
    ],
    databases: [
        'postgres'
    ],
    techIcons: [],
    imageUrls:[],
    modalLink: '#animatedModal-2',
    modalId: 'modal02',
   },
   {
    name: 'Online Job Portal',
    date: '',
    description: 'Web application where job seekers can search and apply for jobs. Employers can post jobs and view appilcants.',
    mainImage: 'images/fulls/online-job-portal.png',
    mainUrl: '',
    documentsLinks: [],
    github: 'https://github.com/dwoods447/vue-job-portal',
    skillsUsed: [
        'vue.js',
        'node.js',
        'express.js',
        'vuetify',
        'vee-validate',
        'vue-router',
        'axios'
    ],
    databases: [
        'mysql'
    ],
    techIcons: [],
    imageUrls:[],
    modalLink: '',
    modalId: '',
   },
      {
    name: 'Universty of Houston\'s Class Search App',
    date: '',
    description: 'The online hybrid, and session class search was designed and build by me to help UH students quickly find classes that fit their schedule.',
    mainImage: './images/fulls/class-search-university-of-houston.png',
    mainUrl: 'https://uh.edu/online/sessions/class-search/',
    documentsLinks: [],
    github: '',
    skillsUsed: [
        'vue.js',
        'axios',
        'laravel',
        'php',
        'vee-validate',
        'pretty-checkbox',
        'vue-paginate'
    ],
    databases: [
       'mysql'
    ],
    techIcons: [],
    imageUrls:[],
    modalLink: '',
    modalId: '',
   },
   {
    name: 'Saiyan Spectator 2.0',
    date: '',
    description: 'Personal Dragonball fansite re-built using Laravel 8, PHP7, and Vue 3',
    mainImage: 'images/fulls/saiyan-spectator-2.0.jpg',
    mainUrl: 'http://saiyian-spectator-2-app.herokuapp.com/',
    documentsLinks: [],
    github: 'https://github.com/dwoods447/saiyan-spectator-2.0',
    skillsUsed: [
        'vue.js',
        'laravel',
        'inertia.js'
    ],
    databases: [
        'mysql'
    ],
    techIcons: [],
    imageUrls:[],
    modalLink: '',
    modalId: '',
   },
   //    {
//     name: '',
//     date: '',
//     description: '',
//     mainImage: '',
//     mainUrl: '',
//     documentsLinks: [],
//     github: '',
//     skillsUsed: [
//         'vue.js',
//         'node.js',
//         'express.js',
//         'vuetify',
//         'vee-validate',
//         'vue-router',
//         'axios'
//     ],
//     databases: [],
//     techIcons: [],
//     imageUrls:[],
//     modalLink: '',
//     modalId: '',
//    },
   
]

export default projects